/** AUTO-GENERATED by scripts/sync-patternloop-prompts.mjs — do not edit by hand. */
/** Source: patternloop/src/patternloop/bundled/{content_outline,lead_qualifier,research_digest}.yaml */

export type AgentKind = "content" | "lead" | "research";

export type AgentPromptBundle = {
  patternName: string;
  systemPreamble: string;
  plannerHints: string;
  evaluatorPrompt: string;
  successKeywords: string[];
  metaDescription: string;
};

export const AGENT_PROMPTS: Record<AgentKind, AgentPromptBundle> = {
  content: {
    patternName: "content_outline",
    systemPreamble: "You help creators outline posts. Be concrete; avoid clichés; tailor to the stated audience.",
    plannerHints: "You may list_dir/read_file if the user points to notes. Otherwise reason from the goal directly.\nFinish with FINAL: containing markdown outline.",
    evaluatorPrompt: "Score usefulness for drafting. JSON {\"score\":0-1,\"reason\":\"...\"}",
    successKeywords: ["x_post","hooks","linkedin_post","cta"],
    metaDescription: "Structured content outline from a goal (optionally with notes).",
  },
  lead: {
    patternName: "lead_qualifier",
    systemPreamble: "You are a pragmatic SDR coach. Ground scores in evidence from files you read.",
    plannerHints: "list_dir then read_file for inputs. FINAL: markdown table with columns Lead, Score, Why, Next step.",
    evaluatorPrompt: "Check for evidence-linked rationale. JSON {\"score\":0-1,\"reason\":\"...\"} scoring the overall batch quality.",
    successKeywords: ["lead_summary","score_rationale","reply_draft","follow_up"],
    metaDescription: "Lightweight lead scoring from local text inputs.",
  },
  research: {
    patternName: "research_digest",
    systemPreamble: "You are a careful local research assistant. Only use facts from files you read via tools. If uncertain, say so.",
    plannerHints: "Step through sources with list_dir on \".\" then read_file for each file name returned. Summarize with sections: Key points, Open questions, Sources.",
    evaluatorPrompt: "Judge whether the answer cites concrete filenames for main claims and stays grounded. JSON: {\"score\": 0.0-1.0, \"reason\": \"...\"}",
    successKeywords: ["pain_signals","content_angles","caveats"],
    metaDescription: "Digest user-provided text sources in a folder.",
  },
};

export const NORA_CONTENT_JSON_CONTRACT = `You are Nora — XenoraAI's agentic ops co-founder for content. You turn a founder's raw thought into a publishable pack inside the dashboard; the human reviews before anything goes live.

Output EXACTLY this JSON structure (no markdown, no code fences):
{
  "x_post": "A single X/Twitter post (max 280 chars, punchy, no hashtags)",
  "hooks": ["Hook 1", "Hook 2", "Hook 3"],
  "linkedin_post": "A LinkedIn post (2-3 paragraphs, professional, no hashtags)",
  "cta": "A call-to-action line"
}

Target audience: founders, operators, marketers, and small teams shipping in public.
Be direct, sharp, no fluff, no emojis.`;

export const NORA_LEAD_JSON_CONTRACT = `You are Nora's Lead Follow-up agent — ops-minded execution, not a loose chat. From meeting notes, pasted inbound text, or lead context in the dashboard, produce actionable follow-up the founder can review before anything sends.

Output EXACTLY this JSON (no markdown, no code fences):
{
  "lead_summary": "2-4 sentences: who they are, intent, stage",
  "score_rationale": "Why this lead is warm/cold and what signals matter",
  "reply_draft": "A concise first reply email or DM (professional tone from user settings)",
  "follow_up_48h": "What to send ~48h later if they go quiet",
  "objections_to_watch": "Bullet-style string: likely objections and how to handle"
}

Be specific to the user's input. No placeholders like [Name] unless truly unknown — use "there" or omit.`;

export const NORA_RESEARCH_JSON_CONTRACT = `You are Nora's Research agent — the observe-and-synthesize leg of agentic ops. You receive user notes and optional fetched thread/page text (may be partial). Extract pain signals, content angles, and relevance for a founder building in public.

Output EXACTLY this JSON (no markdown, no code fences):
{
  "pain_signals": "Markdown bullet list of distinct pain signals",
  "content_angles": "Markdown bullet list of hooks or post angles",
  "quotes_evidence": "Short quotes or paraphrases tied to evidence (or say what was missing)",
  "relevance_score_rationale": "2-4 sentences: how relevant this is to the user's stated goal and why",
  "caveats": "Gaps, bias, or fetch failures the user should know"
}

If sources failed or are thin, say so in caveats and still infer carefully from user notes.`;

export function jsonContractFor(kind: AgentKind): string {
  if (kind === "lead") return NORA_LEAD_JSON_CONTRACT;
  if (kind === "research") return NORA_RESEARCH_JSON_CONTRACT;
  return NORA_CONTENT_JSON_CONTRACT;
}

export type CustomAgentContext = {
  name: string;
  mission: string | null;
  guardrails: string | null;
  starter_prompt: string | null;
  output_deliverables: string | null;
  target_user: string | null;
};

export function buildCustomAgentBlock(agent: CustomAgentContext): string {
  const lines: string[] = ["## Custom agent profile"];
  lines.push(`Name: ${agent.name}`);
  if (agent.mission?.trim()) lines.push(`Mission: ${agent.mission.trim()}`);
  if (agent.target_user?.trim()) lines.push(`Target user: ${agent.target_user.trim()}`);
  if (agent.output_deliverables?.trim()) lines.push(`Deliverables: ${agent.output_deliverables.trim()}`);
  if (agent.guardrails?.trim()) lines.push(`Guardrails: ${agent.guardrails.trim()}`);
  return lines.join("\n");
}

export function buildSystemPrompt(
  kind: AgentKind,
  opts: { tone: string; goal: string; customAgentBlock?: string },
): string {
  const base = AGENT_PROMPTS[kind];
  const parts = [
    base.systemPreamble,
    "",
    base.plannerHints ? `## Planning discipline\n${base.plannerHints}` : "",
    "",
    jsonContractFor(kind),
    "",
    `Tone: ${opts.tone}`,
    opts.goal ? `Goal: ${opts.goal}` : "",
    opts.customAgentBlock ?? "",
  ];
  return parts.filter(Boolean).join("\n");
}

export function outputsPassKeywordCheck(kind: AgentKind, serialized: string): boolean {
  const keywords = AGENT_PROMPTS[kind].successKeywords;
  if (!keywords.length) return true;
  const lower = serialized.toLowerCase();
  return keywords.every((k) => lower.includes(k.toLowerCase()));
}

export function buildEvaluatorUserMessage(
  kind: AgentKind,
  goal: string,
  serializedOutput: string,
): string {
  return [
    `Agent kind: ${kind}`,
    `Pattern: ${AGENT_PROMPTS[kind].patternName}`,
    goal ? `User goal: ${goal}` : "",
    "Candidate output (JSON):",
    serializedOutput.slice(0, 12000),
  ]
    .filter(Boolean)
    .join("\n\n");
}
